-- Generated SQL for Disruptors AI Marketing Hub Content

-- Team Members
INSERT INTO public.team_members (name, title, bio, headshot, social_links, is_active, display_order) VALUES
('Will Stevens', 'CEO & AI Strategy Director', 'Leading AI transformation initiatives for marketing teams worldwide. Specializing in implementing cutting-edge AI solutions that drive measurable business growth.', 'https://res.cloudinary.com/dvcvxhzmt/image/upload/f_auto,q_auto/disruptors-media/team/will-stevens.jpg', '{"linkedin":"https://linkedin.com/in/willstevens"}', true, 1)
ON CONFLICT (name) DO UPDATE SET
title = EXCLUDED.title, bio = EXCLUDED.bio, headshot = EXCLUDED.headshot, social_links = EXCLUDED.social_links;

INSERT INTO public.team_members (name, title, bio, headshot, social_links, is_active, display_order) VALUES
('Sarah Chen', 'Head of AI Development', 'Expert in machine learning and AI model optimization. Sarah leads our technical team in developing custom AI solutions for enterprise clients.', 'https://res.cloudinary.com/dvcvxhzmt/image/upload/f_auto,q_auto/disruptors-media/team/sarah-chen.jpg', '{"linkedin":"https://linkedin.com/in/sarahchen"}', true, 2)
ON CONFLICT (name) DO UPDATE SET
title = EXCLUDED.title, bio = EXCLUDED.bio, headshot = EXCLUDED.headshot, social_links = EXCLUDED.social_links;

INSERT INTO public.team_members (name, title, bio, headshot, social_links, is_active, display_order) VALUES
('Marcus Rodriguez', 'Creative AI Director', 'Pioneering the intersection of creativity and artificial intelligence. Marcus oversees all AI-generated content and visual strategy initiatives.', 'https://res.cloudinary.com/dvcvxhzmt/image/upload/f_auto,q_auto/disruptors-media/team/marcus-rodriguez.jpg', '{"linkedin":"https://linkedin.com/in/marcusrodriguez"}', true, 3)
ON CONFLICT (name) DO UPDATE SET
title = EXCLUDED.title, bio = EXCLUDED.bio, headshot = EXCLUDED.headshot, social_links = EXCLUDED.social_links;

INSERT INTO public.team_members (name, title, bio, headshot, social_links, is_active, display_order) VALUES
('Emma Thompson', 'Data Analytics Manager', 'Transforms complex data into actionable insights that drive strategic decision-making. Emma specializes in predictive analytics and performance optimization.', 'https://res.cloudinary.com/dvcvxhzmt/image/upload/f_auto,q_auto/disruptors-media/team/emma-thompson.jpg', '{"linkedin":"https://linkedin.com/in/emmathompson-analytics"}', true, 4)
ON CONFLICT (name) DO UPDATE SET
title = EXCLUDED.title, bio = EXCLUDED.bio, headshot = EXCLUDED.headshot, social_links = EXCLUDED.social_links;

INSERT INTO public.team_members (name, title, bio, headshot, social_links, is_active, display_order) VALUES
('James Wilson', 'Client Success Director', 'Ensures every client achieves exceptional results through personalized strategies and dedicated support. James brings over 8 years of experience in customer success.', 'https://res.cloudinary.com/dvcvxhzmt/image/upload/f_auto,q_auto/disruptors-media/team/james-wilson.jpg', '{"linkedin":"https://linkedin.com/in/jameswilson-success"}', true, 5)
ON CONFLICT (name) DO UPDATE SET
title = EXCLUDED.title, bio = EXCLUDED.bio, headshot = EXCLUDED.headshot, social_links = EXCLUDED.social_links;

-- Services
INSERT INTO public.services (name, slug, description, short_description, category, featured_image, is_active, features, benefits, seo_title, seo_description, seo_keywords) VALUES
('AI Automation & Infrastructure', 'ai-automation', 'Our AI automation services help businesses streamline operations, generate leads, and scale with efficiency by integrating advanced tools like GoHighLevel, n8n, and custom AI systems. We design tailored solutions that eliminate repetitive tasks, enhance customer engagement, and drive measurable ROI. Whether you need automated marketing, CRM workflows, or AI-powered content systems, we create scalable infrastructure that grows with your business.', 'Streamline. Automate. Scale.', 'automation', 'https://res.cloudinary.com/dvcvxhzmt/image/upload/f_auto,q_auto/disruptors-media/services/graphics/hand-human.png', true, '{"Custom AI Systems","GoHighLevel Integration","n8n Workflows","CRM Automation","Lead Generation","Content Systems"}', '{"Eliminate repetitive tasks","Enhanced customer engagement","Measurable ROI","Scalable infrastructure"}', 'AI Automation & Infrastructure - Build Your AI-Powered Future', 'Streamline operations, generate leads, and scale with efficiency using AI automation services. Custom AI systems, CRM workflows, and automated marketing solutions.', '{"AI automation","business automation","CRM workflows","lead generation","GoHighLevel","custom AI systems"}')
ON CONFLICT (slug) DO UPDATE SET
name = EXCLUDED.name, description = EXCLUDED.description, short_description = EXCLUDED.short_description;

INSERT INTO public.services (name, slug, description, short_description, category, featured_image, is_active, features, benefits, seo_title, seo_description, seo_keywords) VALUES
('Fractional CMO', 'fractional-cmo', 'Get the benefit of a seasoned Chief Marketing Officer without the full-time executive salary. Our Fractional CMO service provides the high-level strategy, team leadership, and data-driven insights you need to scale your marketing efforts effectively. We work as an extension of your team to guide your marketing vision, manage execution, and ensure every initiative is aligned with your business objectives.', 'Executive Level Marketing, at a Fraction of the Cost', 'strategy', 'https://res.cloudinary.com/dvcvxhzmt/image/upload/f_auto,q_auto/disruptors-media/services/graphics/services-img.png', true, '{"Strategic Marketing Leadership","Team Management","Data-Driven Insights","Marketing Vision Guidance","Execution Management","Business Alignment"}', '{"Seasoned expertise without full-time costs","High-level strategy","Effective scaling","Team leadership"}', 'Fractional CMO Services - Strategic Leadership on Demand', 'Get seasoned Chief Marketing Officer expertise without the full-time salary. Strategic leadership, team management, and data-driven marketing insights.', '{"fractional CMO","marketing strategy","chief marketing officer","marketing leadership","strategic marketing","marketing consulting"}')
ON CONFLICT (slug) DO UPDATE SET
name = EXCLUDED.name, description = EXCLUDED.description, short_description = EXCLUDED.short_description;

INSERT INTO public.services (name, slug, description, short_description, category, featured_image, is_active, features, benefits, seo_title, seo_description, seo_keywords) VALUES
('CRM Management', 'crm-management', 'Transform your customer relationships with our comprehensive CRM management services. We implement, optimize, and maintain CRM systems that streamline your sales process, improve customer retention, and provide actionable insights for business growth.', 'Streamline Customer Relationships and Sales Processes', 'management', '', true, '{"CRM Implementation","Sales Process Optimization","Customer Data Management","Automated Workflows","Analytics & Reporting","Integration Services"}', '{"Improved customer retention","Streamlined sales processes","Actionable business insights","Enhanced productivity"}', 'CRM Management Services - Transform Customer Relationships', 'Comprehensive CRM management services to streamline sales processes, improve customer retention, and provide actionable business insights.', '{"CRM management","customer relationship management","sales optimization","CRM implementation","customer retention","sales automation"}')
ON CONFLICT (slug) DO UPDATE SET
name = EXCLUDED.name, description = EXCLUDED.description, short_description = EXCLUDED.short_description;

INSERT INTO public.services (name, slug, description, short_description, category, featured_image, is_active, features, benefits, seo_title, seo_description, seo_keywords) VALUES
('Custom Apps', 'custom-apps', 'Build powerful custom applications tailored to your unique business needs. Our development team creates scalable, user-friendly applications that integrate seamlessly with your existing systems and workflow.', 'Tailored Applications for Unique Business Needs', 'development', '', true, '{"Custom Development","System Integration","Scalable Architecture","User-Friendly Design","API Development","Database Design"}', '{"Tailored to your needs","Seamless integration","Scalable solutions","Enhanced productivity"}', 'Custom App Development - Tailored Business Solutions', 'Build powerful custom applications tailored to your business needs. Scalable, user-friendly apps with seamless system integration.', '{"custom app development","business applications","software development","system integration","custom software","app development"}')
ON CONFLICT (slug) DO UPDATE SET
name = EXCLUDED.name, description = EXCLUDED.description, short_description = EXCLUDED.short_description;

INSERT INTO public.services (name, slug, description, short_description, category, featured_image, is_active, features, benefits, seo_title, seo_description, seo_keywords) VALUES
('Paid Advertising', 'paid-advertising', 'Maximize your ROI with data-driven paid advertising campaigns across Google Ads, Facebook, LinkedIn, and other platforms. Our advertising experts create, manage, and optimize campaigns that drive qualified leads and conversions.', 'Data-Driven Campaigns That Drive Results', 'advertising', '', true, '{"Google Ads Management","Social Media Advertising","Campaign Optimization","A/B Testing","Conversion Tracking","ROI Analysis"}', '{"Maximized ROI","Qualified lead generation","Data-driven optimization","Multi-platform reach"}', 'Paid Advertising Services - Maximize ROI with Expert Campaigns', 'Data-driven paid advertising campaigns across Google Ads, Facebook, LinkedIn. Expert management and optimization for maximum ROI.', '{"paid advertising","Google Ads","Facebook ads","PPC management","digital advertising","campaign optimization"}')
ON CONFLICT (slug) DO UPDATE SET
name = EXCLUDED.name, description = EXCLUDED.description, short_description = EXCLUDED.short_description;

INSERT INTO public.services (name, slug, description, short_description, category, featured_image, is_active, features, benefits, seo_title, seo_description, seo_keywords) VALUES
('Lead Generation', 'lead-generation', 'Generate high-quality leads that convert with our comprehensive lead generation strategies. We combine content marketing, SEO, paid advertising, and automation to create a steady stream of qualified prospects for your business.', 'Generate High-Quality Leads That Convert', 'marketing', '', true, '{"Multi-Channel Strategy","Lead Qualification","Content Marketing","SEO Optimization","Marketing Automation","Performance Tracking"}', '{"High-quality prospects","Steady lead flow","Improved conversion rates","Comprehensive tracking"}', 'Lead Generation Services - Generate High-Quality Prospects', 'Comprehensive lead generation strategies combining content marketing, SEO, paid advertising, and automation for qualified prospects.', '{"lead generation","prospect generation","marketing automation","content marketing","SEO lead generation","qualified leads"}')
ON CONFLICT (slug) DO UPDATE SET
name = EXCLUDED.name, description = EXCLUDED.description, short_description = EXCLUDED.short_description;

INSERT INTO public.services (name, slug, description, short_description, category, featured_image, is_active, features, benefits, seo_title, seo_description, seo_keywords) VALUES
('SEO & Local SEO', 'seo-geo', 'Dominate local search results and improve your online visibility with our comprehensive SEO and local SEO services. We optimize your website, manage your local listings, and create content strategies that drive organic traffic and local customers.', 'Dominate Local Search and Online Visibility', 'seo', '', true, '{"Local SEO Optimization","Google My Business","Citation Management","Content Strategy","Technical SEO","Keyword Research"}', '{"Improved search rankings","Increased local visibility","Higher organic traffic","More local customers"}', 'SEO & Local SEO Services - Dominate Local Search Results', 'Comprehensive SEO and local SEO services to improve online visibility, dominate local search results, and drive organic traffic.', '{"SEO services","local SEO","search engine optimization","Google My Business","local search","organic traffic"}')
ON CONFLICT (slug) DO UPDATE SET
name = EXCLUDED.name, description = EXCLUDED.description, short_description = EXCLUDED.short_description;

INSERT INTO public.services (name, slug, description, short_description, category, featured_image, is_active, features, benefits, seo_title, seo_description, seo_keywords) VALUES
('Podcasting Services', 'podcasting', 'Launch and grow your podcast with our full-service podcasting solutions. From concept development to production, distribution, and promotion, we help you build a powerful podcast that engages your audience and grows your brand.', 'Launch and Grow Your Podcast with Full-Service Solutions', 'content', '', true, '{"Podcast Strategy","Production Services","Audio Editing","Distribution Setup","Promotion Strategy","Analytics Tracking"}', '{"Professional production","Wide distribution reach","Audience engagement","Brand growth"}', 'Podcasting Services - Launch and Grow Your Podcast', 'Full-service podcasting solutions from concept to promotion. Professional production, distribution, and growth strategies for your podcast.', '{"podcasting services","podcast production","podcast launch","audio editing","podcast distribution","podcast growth"}')
ON CONFLICT (slug) DO UPDATE SET
name = EXCLUDED.name, description = EXCLUDED.description, short_description = EXCLUDED.short_description;

INSERT INTO public.services (name, slug, description, short_description, category, featured_image, is_active, features, benefits, seo_title, seo_description, seo_keywords) VALUES
('Social Media Marketing', 'social-media', 'Build your brand and engage your audience with strategic social media marketing. We create compelling content, manage your social media presence, and implement strategies that drive engagement, followers, and conversions across all major platforms.', 'Build Your Brand and Engage Your Audience', 'marketing', '', true, '{"Content Creation","Social Media Management","Community Engagement","Influencer Partnerships","Social Advertising","Analytics & Reporting"}', '{"Increased brand awareness","Higher engagement rates","Follower growth","Improved conversions"}', 'Social Media Marketing - Build Your Brand and Engage Audiences', 'Strategic social media marketing with compelling content creation, management, and engagement strategies across all major platforms.', '{"social media marketing","social media management","content creation","social media strategy","brand engagement","social advertising"}')
ON CONFLICT (slug) DO UPDATE SET
name = EXCLUDED.name, description = EXCLUDED.description, short_description = EXCLUDED.short_description;

-- Case Studies
INSERT INTO public.case_studies (title, slug, client_name, industry, project_type, summary, challenge, solution, results, metrics, services_provided, technologies_used, timeline_months, featured_image, testimonial_quote, testimonial_author, is_featured, is_published, display_order, seo_title, seo_description, seo_keywords) VALUES
('Granite Paving Digital Growth Platform', 'granite-paving', 'Granite Paving', 'Construction & Landscaping', 'Web Development, Digital Marketing, Content', 'Built a comprehensive digital platform that transformed Granite Paving from a local contractor to a regional leader in paving and landscaping services.', 'Limited online presence, manual project management, and difficulty showcasing completed work were restricting business growth and market reach.', 'Created a full digital ecosystem including a showcase website, project management tools, and automated lead generation system with portfolio integration.', 'Achieved 380% increase in lead generation, 65% reduction in project timeline, 250% expansion in service area, and 98% client satisfaction rate.', '{"Lead Generation":"+380%","Project Timeline":"-65%","Service Area":"+250%","Client Satisfaction":"98%"}', '{"Showcase Website","Project Management","Lead Generation"}', '{"Web Development","CRM Integration","Project Management Tools"}', 6, 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=2070&auto=format&fit=crop', 'Our business has grown exponentially since launching the new platform. The project showcases are incredible.', 'Granite Paving', true, true, 1, 'Granite Paving Case Study - Digital Growth Platform Success', 'How we helped Granite Paving achieve 380% lead generation increase through comprehensive digital platform development.', '{"granite paving","digital marketing case study","construction marketing","lead generation","web development"}')
ON CONFLICT (slug) DO UPDATE SET
title = EXCLUDED.title, summary = EXCLUDED.summary;

